SELECT * FROM FUTBOLISTAS;

SELECT NOMBRE FROM FUTBOLISTAS WHERE SALARIO = (SELECT MAX(SALARIO) FROM FUTBOLISTAS); 

SELECT TO_CHAR(FECHA_NACIMIENTO, 'YYYY') FROM FUTBOLISTAS WHERE SALARIO = (SELECT MIN(SALARIO) FROM FUTBOLISTAS);