SELECT TO_NUMBER('1000.45', '9999.99') FROM DUAL;
SELECT TO_NUMBER('1000.45€', '9999.99L') FROM DUAL;
SELECT TO_NUMBER('-$1000.45', 'S$9999.99') FROM DUAL; 
SELECT 
    TO_CHAR(SYSDATE, 'DD/MM/YYYY'),
     
    TO_CHAR(SYSDATE, 'DD/MM/YY'),

    (TO_CHAR(SYSDATE, 'DD') 
    || '-' || 
    TO_CHAR(SYSDATE, 'MON') 
    || '-' || 
    TO_CHAR(SYSDATE, 'YYYY')),

    (TO_CHAR(SYSDATE, 'DD') 
    || ' de ' || 
    TRIM(TO_CHAR(SYSDATE, 'MONTH'))
    || ' de ' || 
    TO_CHAR(SYSDATE, 'YYYY'))

    FROM DUAL;


SELECT TO_NUMBER(SUBSTR(ID, 4)) FROM FUTBOLISTAS;

SELECT TO_CHAR(FECHA_NACIMIENTO, 'YYYY') FROM FUTBOLISTAS ORDER BY FECHA_NACIMIENTO ASC;

