
-- EJECICIO 7
SELECT FUTBOLISTAS.NOMBRE, EQUIPOS.NOMBRE FROM FUTBOLISTAS JOIN EQUIPOS ON FUTBOLISTAS.ID_EQUIPO = EQUIPOS.ID;

-- EJERCICIO 8 
SELECT F.NOMBRE, F.APELLIDOS, E.NOMBRE FROM FUTBOLISTAS F JOIN EQUIPOS E ON F.ID_EQUIPO = E.ID WHERE F.POSICION = 'DEFENSA'; 

-- EJERCICIO 10 

SELECT * FROM FUTBOLISTAS;

SELECT SALARIO "EUROS" FROM FUTBOLISTAS UNION SELECT PRESUPUESTO FROM EQUIPOS ;

-- EJERCICIO 11 

SELECT ESTADIO FROM PARTIDOS INTERSECT SELECT ESTADIO FROM EQUIPOS;