
-- EJECICIO 7
SELECT FUTBOLISTAS.NOMBRE, EQUIPOS.NOMBRE FROM FUTBOLISTAS JOIN EQUIPOS ON FUTBOLISTAS.ID_EQUIPO = EQUIPOS.ID;

-- EJERCICIO 8 
SELECT F.NOMBRE, F.APELLIDOS, E.NOMBRE FROM FUTBOLISTAS F JOIN EQUIPOS E ON F.ID_EQUIPO = E.ID WHERE F.POSICION = 'DEFENSA'; 


-- USANDO DOS SELECT Y UNION, UNE LOS PORTEROS CON LOS DELANTEROS (SELEC 1 SOLO SE TRAE LOS PORTEOS Y LOS 2 SOLO LOS DELANTEROS)

