SELECT * FROM CLIENTES;
SELECT * FROM AVANCES_LINEAS_FABRICACION;
SELECT * FROM MAQUINAS;
-- 1 

SELECT NOMBRE_EMPRESA, MAQUINAS.PRECIO_VENTA FROM CLIENTES JOIN 
    AVANCES_LINEAS_FABRICACION ALF 
    ON ALF.ID_CLIENTE = CLIENTES.CIF 
    JOIN MAQUINAS ON MAQUINAS.REF = ALF.ID_MAQUINA
    WHERE ESTADO = 'PUESTA A PUNTO' 
    AND ALF.LINEA_FABRICACION = 2
    AND TO_CHAR(FECHA, 'YYYY') = '2023';  

SELECT NOMBRE_EMPRESA, SUM(PRECIO_VENTA) FROM MAQUINAS LEFT JOIN AVANCES_LINEAS_FABRICACION ALP 
    ON ALP.ID_MAQUINA = MAQUINAS.REF
    LEFT JOIN CLIENTES ON ALP.ID_CLIENTE = CLIENTES.CIF 
    GROUP BY CLIENTES.NOMBRE_EMPRESA;

SELECT * FROM PIEZAS;
SELECT TIPO, ESTADO, COUNT(*) FROM PIEZAS GROUP BY TIPO, ESTADO;


DECLARE
    TYPE INFORMACION IS RECORD (
        EXISTE INT,
        NOMBRE_USUARIO CLIENTES.NOMBRE_EMPRESA%TYPE,
        NUM_TOTAL_AVANCES INT,
        ID_USUARIO CLIENTES.CIF%TYPE 
    );

    INFO INFORMACION;
BEGIN
    INFO.NOMBRE_USUARIO := '&NOMBRE_RECIBIDO';
    SELECT COUNT(*) INTO INFO.EXISTE FROM CLIENTES WHERE NOMBRE_EMPRESA = INFO.NOMBRE_USUARIO;

    IF INFO.EXISTE >= 1 THEN
        SELECT CIF INTO INFO.ID_USUARIO FROM CLIENTES WHERE NOMBRE_EMPRESA = INFO.NOMBRE_USUARIO;
        SELECT COUNT(*) INTO INFO.NUM_TOTAL_AVANCES FROM AVANCES_LINEAS_FABRICACION WHERE ID_CLIENTE = INFO.ID_USUARIO;

        DBMS_OUTPUT.PUT_LINE('HAY ' || INFO.NUM_TOTAL_AVANCES || ' LINEAS PARA EL CLIENTE ' || INFO.NOMBRE_USUARIO || ' , SIENDO ' 
            || INFO.NUM_TOTAL_AVANCES || ' EL NUMERO TOTAL DE ESOS AVANCES DE ESE CLIENTE Y ' || INFO.NOMBRE_USUARIO || ' EL NOMBRE DE CLIENTE');
    ELSE 
        DBMS_OUTPUT.PUT_LINE('No existe ese cliente');
    END IF; 
END;
/

UNDEFINE NOMBRE_RECIBIDO;


DECLARE 
    EXISTE INT;
    MES VARCHAR2(50) := UPPER('&MESRECIBIDO');
    PRECIO_MAQUINA INT;
BEGIN
    SELECT COUNT(*) INTO EXISTE FROM AVANCES_LINEAS_FABRICACION WHERE UPPER(TRIM(TO_CHAR(FECHA, 'MONTH'))) = MES;

    IF EXISTE >= 1 THEN 
        SELECT MAX(PRECIO_VENTA) INTO PRECIO_MAQUINA FROM MAQUINAS JOIN AVANCES_LINEAS_FABRICACION ALF 
            ON ALF.ID_MAQUINA = MAQUINAS.REF WHERE TRIM(UPPER(TO_CHAR(FECHA, 'MONTH'))) = MES;
        DBMS_OUTPUT.PUT_LINE(PRECIO_MAQUINA);
    ELSE
        DBMS_OUTPUT.PUT_LINE('NO EXISTE');
    END IF;
END;
/

UNDEFINE MESRECIBIDO;

SELECT * FROM MAQUINAS;
SELECT * FROM AVANCES_LINEAS_FABRICACION;