-- PARTE 1

DROP TABLE PILOTOS CASCADE CONSTRAINTS; 
CREATE TABLE PILOTOS (
    ID INT PRIMARY KEY,
    NOMBRE VARCHAR2(50),
    APELLIDOS VARCHAR2(50),
    FECHA_NACIMIENTO DATE, 
    NACIONALIDAD VARCHAR2(50),
    ID_ROL INT, 
    ID_EQUIPO INT
);


DROP TABLE EQUIPOS CASCADE CONSTRAINTS; 
CREATE TABLE EQUIPOS (
    ID INT PRIMARY KEY, 
    NOMBRE VARCHAR2(50),
    SEDE VARCHAR2(50),
    DIRECTOR VARCHAR2(50),
    MOTOR VARCHAR2(50),
    NUM_TITULOS INT,
    NUM_EMPLEADOS INT
);

DROP TABLE ROLES CASCADE CONSTRAINT;
CREATE TABLE ROLES (
    ID INT PRIMARY KEY,
    ROL VARCHAR2(50)
);

ALTER TABLE PILOTOS ADD CONSTRAINT "PILOTO_ROLES_FK" FOREIGN KEY (ID_ROL) REFERENCES ROLES (ID);
ALTER TABLE PILOTOS ADD CONSTRAINT "PILOTO_EQUIPOS_FK" FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPOS (ID);
ALTER TABLE EQUIPOS ADD CONSTRAINT "CHECKEMPS" CHECK (NUM_EMPLEADOS > 0);


INSERT INTO PILOTOS VALUES (1, 'FERNANDO', 'ALONSO', '29/07/1981', 'ESPAÑOLA', 1, 1);
INSERT INTO PILOTOS VALUES (2, 'MAX', 'VERSTAPPEN', '30/09/1997', 'HOLANDESA', 1, 2);
INSERT INTO PILOTOS VALUES (3, 'LEWIS', 'HAMILTON', '07/01/1985', 'BRITÁNICA', 1, 3);
INSERT INTO PILOTOS VALUES (4, 'CARLOS', 'SAINZ', '01/09/1994', 'ESPAÑOLA', 1, 4);


INSERT INTO EQUIPOS VALUES (1, 'ASTON MARTIN', 'SILVERSTONE', 'ADRIAN NEWEY', 'MERCEDES', 0, 800);
INSERT INTO EQUIPOS VALUES (2, 'RED BULL', 'MILTON KEYNES', 'CHRISTIAN HORNER', 'HONDA', 6, 1000);
INSERT INTO EQUIPOS VALUES (3, 'FERRARI', 'MARANELLO', 'JOHN ELKANN', 'FERRARI', 16, 1200);
INSERT INTO EQUIPOS VALUES (4, 'WILLIAMS', 'GROVE', 'JAMES VOWLES', 'MERCEDES', 9, 750);


INSERT INTO ROLES VALUES (1, 'PRIMER PILOTO');
INSERT INTO ROLES VALUES (2, 'SEGUNDO PILOTO');
INSERT INTO ROLES VALUES (3, 'PILOTO PRUEBAS');


COMMIT;

-- PARTE 2 

SELECT NACIONALIDAD, COUNT(*) FROM PILOTOS GROUP BY NACIONALIDAD ORDER BY COUNT(*) DESC, NACIONALIDAD; 

SELECT PILOTOS.APELLIDOS, PILOTOS.NOMBRE || ' - ' || EQUIPOS.NOMBRE  FROM PILOTOS 
    LEFT JOIN EQUIPOS ON EQUIPOS.ID = PILOTOS.ID_EQUIPO 
    LEFT JOIN ROLES ON ROLES.ID = PILOTOS.ID_ROL 
    WHERE ROLES.ROL = 'PRIMER PILOTO';

SELECT MOTOR || ' - ' || NUM_TITULOS  FROM EQUIPOS;

SELECT COUNT(*) FROM PILOTOS WHERE MOD(TO_CHAR(FECHA_NACIMIENTO, 'DD'), 2) != 0;

SELECT P.NOMBRE, P.APELLIDOS, E.DIRECTOR, R.ROL FROM PILOTOS P 
    LEFT JOIN EQUIPOS E ON E.ID = P.ID_EQUIPO
    LEFT JOIN ROLES R ON R.ID = P.ID_ROL;



SELECT * FROM EQUIPOS;
SELECT * FROM PILOTOS;
SELECT LENGTH(APELLIDOS) - LENGTH(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(APELLIDOS,'A', ''), 'E', ''), 'I', ''), 'O', ''), 'U', ''))
    LEFT JOIN EQUIPOS WHERE EQUIPOS.ID_EQUIPO = PILOTOS.ID HAVING EQUIPOS.NUM_EMPLEADOS ORDER BY ASC
    FROM PILOTOS;
    

-- SELECT * FROM FUTBOLISTAS JOIN EQUIPOS ON EQUIPOS.ID = FUTBOLISTAS.ID_EQUIPO