DECLARE 
    NUMERO INT := 7; -- DECLARAR E INICIALIZAR  
    NUMERO2 INT;


BEGIN 
    NUMERO2 := 4;
    DBMS_OUTPUT.PUT_LINE(NUMERO);
    NUMERO := 12;
    DBMS_OUTPUT.PUT_LINE(NUMERO); 
    DBMS_OUTPUT.PUT_LINE(NUMERO || ' - ' || NUMERO2);  
END; 
/



--ejercicio 3

set serveroutput on;

declare
    VARIABLE1 EMP.ENAME%TYPE; --variable1 varchar2(10)
    VARIABLE2 EMP%ROWTYPE; --variable2.empno, variable2.ename, etc.
begin
    SELECT ENAME INTO VARIABLE1 FROM EMP WHERE EMPNO = 7839;
    dbms_output.put_line('PRIMER CASO' || VARIABLE1);
    SELECT * INTO VARIABLE2 FROM EMP WHERE EMPNO = 7698;   
    dbms_output.put_line('SEGUNDO CASO' || VARIABLE2.ENAME);
end;
/


DECLARE
    ALTURA INT := &ALTURA; 
    BASE INT := &BASE; 
BEGIN
    DBMS_OUTPUT.PUT_LINE('EL AREA DEL TRIANGULO ES ' || (ALTURA*BASE)/2);
END;
/
UNDEFINE BASE; -- NECESARIO PARA BORRAR CACHE
UNDEFINE ALTURA; -- NECESARIO PARA BORRAR CACHE

--SELECT ENAME FROM EMP WHERE EMPNO = 7839;
-- SELECT * FROM EMP WHERE EMPNO = 7698;