SELECT ROUND(AVG(SALARIO)) FROM FUTBOLISTAS GROUP BY POSICION HAVING ROUND(AVG(SALARIO)) IS NOT NULL;

SELECT * FROM FUTBOLISTAS;

SELECT COUNT(*) FROM FUTBOLISTAS GROUP BY ID_EQUIPO;

SELECT COUNT(*) FROM FUTBOLISTAS GROUP BY ID_EQUIPO HAVING ID_EQUIPO BETWEEN 1 AND 2;

