SELECT EXTRACT (DAY FROM SYSDATE) "DIA", EXTRACT (MONTH FROM SYSDATE) "MES", EXTRACT(YEAR FROM SYSDATE) "AÑO" FROM FUTBOLISTAS;  

SELECT ADD_MONTHS(SYSDATE, 6) FROM FUTBOLISTAS;

SELECT * FROM FUTBOLISTAS;

SELECT FLOOR(MONTHS_BETWEEN(SYSDATE, FECHA_NACIMIENTO)) "DIF MESES" FROM FUTBOLISTAS;

SELECT LAST_DAY(SYSDATE) "ULTIMO DIA" FROM FUTBOLISTAS;

SELECT NEXT_DAY(SYSDATE, 'MON') "PROXIMO LUNES" FROM FUTBOLISTAS; 


SELECT  
    ABS(TO_NUMBER(EXTRACT(YEAR FROM (SELECT FECHA_NACIMIENTO FROM FUTBOLISTAS WHERE NOMBRE = 'PEDRO LUIS'))) 
    -
    TO_NUMBER(EXTRACT(YEAR FROM (SELECT FECHA_NACIMIENTO FROM FUTBOLISTAS WHERE NOMBRE = 'JESUS')))) "AÑOS QUE SE LLEVAN"
    FROM DUAL;  


SELECT  SYSDATE - 4 "HACE 4 DIAS", SYSDATE + 1 "DIA DE MAÑANA" FROM FUTBOLISTAS;
